name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Hello! Thank you for opening your first issue here. We appreciate your contribution and will address it as soon as possible."
        pr-message: "🎉 Thank you for your first pull request! We value your effort and will review it shortly."
